export const colors = {
  primary: "#16A34A",
  primaryPressed: "#0E7A3B",
  primaryDark: "#0E7A3B",
  primaryDeep: "#064E3B",
  primarySoft: "#DCFCE7",
  primarySoftMuted: "#ECFDF3",
  accent: "#FBBF24",
  accentPressed: "#F59E0B",
  accentSoft: "#FFFBEB",
  success: "#16A34A",
  successSoft: "#DCFCE7",
  danger: "#B91C1C",
  dangerSoft: "#FEF2F2",
  background: "#F8F9F4",
  surface: "#FFFFFF",
  surfaceMuted: "#F0F4ED",
  text: "#183D32",
  textMuted: "#586B63",
  textOnPrimary: "#FFFFFF",
  border: "#DDEAE1",
  borderStrong: "#B9D9C3",
  disabled: "#CBD5E1",
  disabledText: "#64748B",
  transparent: "transparent",
} as const;
